# .travis.yaml
language: python
sudo: false

env:
  - LUA="lua=5.1"

before_install:
  - pip install hererocks
  - hererocks lua_install -rlatest --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin

after_failure:
  - curl -v -H User-Agent:bot -H Content-Type:application/json -d '{"content":"Build failed!"}' https://discordapp.com/api/webhooks/469326007745249290/0K92Jqg0kznesVj3Dp7f3FtzSORjc7S0BHRqQo2LPJYYlaEJOalwLhO8uALpdltazQ6O
after_success:
  - curl -v -H User-Agent:bot -H Content-Type:application/json -d '{"content":"Build completed!"}' https://discordapp.com/api/webhooks/469326007745249290/0K92Jqg0kznesVj3Dp7f3FtzSORjc7S0BHRqQo2LPJYYlaEJOalwLhO8uALpdltazQ6O

install:
  - luarocks install busted

script:
  - busted --verbose

notifications:
  slack: auctionator:BC1zZn6yPmF6GNk303gvkOMy#builds

before_deploy:
  - mkdir -p Deploy/Auctionator
  - rsync -av --progress . Deploy/Auctionator --exclude .travis.yml --exclude README.md --exclude Deploy --exclude lua_install --exclude .git --exclude spec --exclude .gitignore --exclude .github
  - mkdir latest
  - cd Deploy && zip -r ../latest/Auctionator.zip * && cd ..

deploy:
  provider: s3
  region: "us-west-1"
  skip_cleanup: true
  detect_encoding: true
  access_key_id: AKIAJBVTKN4IPSXK73KA
  secret_access_key:
    secure: j96xYx9xQ6zLMv0POoa+S6KZaK7QSw9oIekjjcrxbZJJ4ipDsiQ2DcmAN2PzBO2HnPltZpsEEszeD7FB+AuyNVyhJhNg/cRCBh4+Fv77xSCod4WzntITACDQBDHVxkMLVVsoKzScXfDUEKRR1nRY29Vg7S0+Ol6bwihSKl0bcjQsoc5BTmjXZdNK0OIQTZo13ghdYXX41aF4LOl7jWbXcYWxqmMhoUR12OBOUI3Nt8rTQWJTR9W8TLhnSehED0zefvkNrCq/gia0iD3MyDCfiuMPv/ZRrW42NMAr00sOLJs+sfQb3gNgRvMFx4Wwl7z6aBU5qrhCgJNxZ/UIIo2ou9FX/02QpRaua2ypoSOvuTPcj4MI2/dWmjeeuNOXVpUZSImse9jENr5qw6Op5p8BDdpzxOX7dM0nYwM0F3j8W2HNICobW5sVTkELMgeJDPhoT6Zuthxg0R7n4YQXPBVyEXtrwMxjoISWqLyUng89Y6HHclgRk3R6b14iw1eMo9Ghw1YuLc8SB/u8Y66ib8aWkjQNV5uvvFK60KAp2zgNiktGvmRD0T1FoJIrwfjTuIt9Z+/HuyYF8GEa8E59WJjQpzLi3uw0pbnVJ72frYCny/6VOph/oCdU+q580wj944f9tlQs79xF8XgVs0KXXgaGEONC689CCCRAFNDx0M5qGuY=
  bucket: auctionator
  local-dir: latest
  acl: public_read
  on:
    repo: Auctionator/Auctionator
