# .travis.yaml
language: python
sudo: false

env:
  - LUA="lua=5.1"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin

install:
  - luarocks install busted

script:
  - busted --verbose
  - rsync -av --progress . Deploy --exclude Deploy
  - rm -rf Deploy/.git Deploy/spec Deploy/.travis.yml Deploy/README.md
  - zip -r Auctionator.zip Deploy/*

notifications:
  slack: auctionator:BC1zZn6yPmF6GNk303gvkOMy
