# .travis.yaml
language: python
sudo: false

env:
  - LUA="lua=5.1"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin

install:
  - luarocks install busted

script:
  - busted --verbose
  - rsync -av --progress . Deploy --exclude .travis.yml --exclude README.md --exclude Deploy --exclude lua_install --exclude .git --exclude spec
  - zip -r Auctionator.zip Deploy/*

notifications:
  slack: auctionator:BC1zZn6yPmF6GNk303gvkOMy
