Auctionator.ShoppingLists.Events = {
  ListSelected = "AUCTIONATOR_LIST_SELECTED",
  ListDeleted = "AUCTIONATOR_LIST_DELETED",
  ListCreated = "AUCTIONATOR_LIST_CREATED",

  ListItemAdded = "AUCTIONATOR_LIST_ITEM_ADDED",
  ListItemDeleted = "AUCTIONATOR_LIST_ITEM_DELETED",
  DeleteFromList = "AUCTIONATOR_DELETE_FROM_CURRENT_LIST",

  ListSearchStarted = "AUCTIONATOR_LIST_SEARCH_STARTED",
  ListSearchIncrementalUpdate = "AUCTIONATOR_LIST_SEARCH_INCREMENTAL_UPDATE",
  ListSearchEnded = "AUCTIONATOR_LIST_SEARCH_ENDED",
  ListSearchRequested = "AUCTIONATOR_LIST_SEARCH_REQUESTED"
}