Auctionator.ShoppingLists.Events = {
  ListSelected = "AUCTIONATOR_LIST_SELECTED",
  ListDeleted = "AUCTIONATOR_LIST_DELETED",
  ListCreated = "AUCTIONATOR_LIST_CREATED",
  ListRenamed = "AUCTIONATOR_LIST_RENAMED",

  ListItemAdded = "AUCTIONATOR_LIST_ITEM_ADDED",
  ListItemReplaced = "AUCTIONATOR_LIST_ITEM_REPLACED",
  ListItemSelected = "AUCTIONATOR_LIST_ITEM_SELECTED",
  ListItemDeleted = "AUCTIONATOR_LIST_ITEM_DELETED",
  ListOrderChanged = "AUCTIONATOR_LIST_ORDER_CHANGED",
  DeleteFromList = "AUCTIONATOR_DELETE_FROM_CURRENT_LIST",
  EditListItem = "AUCTIONATOR_EDIT_LIST_ITEM",

  ListSearchStarted = "AUCTIONATOR_LIST_SEARCH_STARTED",
  ListSearchIncrementalUpdate = "AUCTIONATOR_LIST_SEARCH_INCREMENTAL_UPDATE",
  ListSearchEnded = "AUCTIONATOR_LIST_SEARCH_ENDED",
  ListSearchRequested = "AUCTIONATOR_LIST_SEARCH_REQUESTED",
  ListDataProviderEmpty = "AUCTIONATOR_LIST_DATA_PROVIDER_EMPTY",

  CreateDialogOnAccept = "AUCTIONATOR_CREATE_DIALOG_ON_ACCEPT",
  DeleteDialogOnAccept = "AUCTIONATOR_DELETE_DIALOG_ON_ACCEPT",
  RenameDialogOnAccept = "AUCTIONATOR_RENAME_DIALOG_ON_ACCEPT",

  DialogOpened = "SHOPPING_DIALOG_OPENED",
  DialogClosed = "SHOPPING_DIALOG_CLOSED",
}
