Auctionator.Constants = {
  History = {
    NUMBER_OF_LINES = 20
  },
  RESULTS_DISPLAY_LIMIT = 100,

  AdvancedSearchDivider = ';',

  PET_CAGE_ID = 82800,

  SCAN_DAY_0 = time({year=2020, month=1, day=1, hour=0}),

  SORT = {
    ASCENDING = 1,
    DESCENDING = 0
  },
  ITEM_TYPES = {
    [0] = "Unknown",
    [1] = "Item",
    [2] = "Commodity"
  },
  ITEM_CLASS_IDS = {
    LE_ITEM_CLASS_WEAPON,
    LE_ITEM_CLASS_ARMOR,
    LE_ITEM_CLASS_CONTAINER,
    LE_ITEM_CLASS_GEM,
    LE_ITEM_CLASS_ITEM_ENHANCEMENT,
    LE_ITEM_CLASS_CONSUMABLE,
    LE_ITEM_CLASS_GLYPH,
    LE_ITEM_CLASS_TRADEGOODS,
    LE_ITEM_CLASS_RECIPE,
    LE_ITEM_CLASS_BATTLEPET,
    LE_ITEM_CLASS_QUESTITEM,
    LE_ITEM_CLASS_MISCELLANEOUS
  },
  INVENTORY_TYPE_IDS = {
    LE_INVENTORY_TYPE_HEAD_TYPE,
    LE_INVENTORY_TYPE_SHOULDER_TYPE,
    LE_INVENTORY_TYPE_CHEST_TYPE,
    LE_INVENTORY_TYPE_WAIST_TYPE,
    LE_INVENTORY_TYPE_LEGS_TYPE,
    LE_INVENTORY_TYPE_FEET_TYPE,
    LE_INVENTORY_TYPE_WRIST_TYPE,
    LE_INVENTORY_TYPE_HAND_TYPE,
  }
}
