Auctionator.Selling.Events.RefreshBuying = "selling_refresh_buying"
Auctionator.Selling.Events.StartFakeBuyLoading = "selling_start_fake_buy_loading"
Auctionator.Selling.Events.StopFakeBuyLoading = "selling_stop_fake_buy_loading"
Auctionator.Selling.Events.PostAttempt = "selling_post_attempt"
Auctionator.Selling.Events.PostSuccessful = "selling_post_successful"
Auctionator.Selling.Events.PostFailed = "selling_post_failed"
