AuctionatorItemHistoryProviderMixin = CreateFromMixins(AuctionatorHistoricalPriceProviderMixin)

function AuctionatorItemHistoryProviderMixin:GetRowTemplate()
  return "AuctionatorResultsRowTemplate"
end

function AuctionatorItemHistoryProviderMixin:GetColumnHideStates()
  return Auctionator.Config.Get(Auctionator.Config.Options.COLUMNS_SHOPPING_HISTORICAL_PRICES)
end
