name: Build

on:
  push:
    branches:
    - master
    tags:
    - '*'

    paths-ignore:
    - "docs/**"
    - ".github/**"

jobs:
  release:
    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        type: [retail, classic, cata]
        include:
          - type: retail
            pkgmeta: .pkgmeta
          - type: cata
            pkgmeta: .pkgmeta_cata
          - type: classic
            pkgmeta: .pkgmeta_vanilla

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: BigWigsMods/packager@master
      with:
        args: -p 6124 -a kRNL70Go -g ${{matrix.type}} -m ${{matrix.pkgmeta}}

