name: Build

on:
  push:
    branches:
    - master
    tags:
    - '*'

    paths-ignore:
    - "docs/**"
    - ".github/**"

jobs:
  strategy:
    matrix:
      type: [retail, wrath, classic]
      include:
        - type: retail
          toc: Auctionator_Mainline.toc
        - type: wrath
          toc: Auctionator_Wrath.toc
        - type: classic
          toc: Auctionator_Vanilla.toc
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup toc
      run: cp ${{matrix.toc}} Auctionator.toc
    - uses: BigWigsMods/packager@v2
      with:
        args: -p 6124 -a kRNL70Go -g ${{matrix.type}}
      env:
        CF_API_KEY: ${{ secrets.plusmouse_curseforge }}
        WAGO_API_TOKEN: ${{ secrets.plusmouse_wago }}
