name: Build

on:
  push:
    branches:
    - master
    tags:
    - '*'

    paths-ignore:
    - "docs/**"
    - ".github/**"

jobs:
  build:
    strategy:
      matrix:
        type: [retail, wrath, classic]
        include:
          - type: retail
            pkgmeta: .pkgmeta
          - type: wrath
            pkgmeta: .pkgmeta_wrath
          - type: cata
            pkgmeta: .pkgmeta_cata
          - type: classic
            pkgmeta: .pkgmeta_vanilla

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: BigWigsMods/packager@v2
      with:
        args: -p 6124 -a kRNL70Go -g ${{matrix.type}} -m ${{matrix.pkgmeta}}
      env:
        CF_API_KEY: ${{ secrets.plusmouse_curseforge }}
        WAGO_API_TOKEN: ${{ secrets.plusmouse_wago }}
