name: Curse Build

on:
  push:
    branches:
    - master

    paths-ignore:
    - "docs/**"
    - ".github/workflows/curse.yml"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: 'Auctionator'
    - run: ./Auctionator/.github/workflows/get-translations.sh frFR
    - run: ./Auctionator/.github/workflows/get-translations.sh deDE
    - run: ./Auctionator/.github/workflows/get-translations.sh itIT
    - run: ./Auctionator/.github/workflows/get-translations.sh koKR
    - run: ./Auctionator/.github/workflows/get-translations.sh zhCN
    - run: ./Auctionator/.github/workflows/get-translations.sh zhTW
    - run: ./Auctionator/.github/workflows/get-translations.sh ruRU
    - run: ./Auctionator/.github/workflows/get-translations.sh esES
    - run: ./Auctionator/.github/workflows/get-translations.sh esMX
    - run: ./Auctionator/.github/workflows/get-translations.sh ptBR
    - name: Delete files for curse
      run: rm -rf Auctionator/README.md Auctionator/.github/ Auctionator/.gitignore Auctionator/.git Auctionator/docs Auctionator/test-data
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{secrets.github_token}}  
    - name: Update version
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "AUTO_GENERATED_VERSION"
        replace: "${{steps.buildnumber.outputs.build_number}} (alpha)"
    - name: Create zip
      run: zip -r Auctionator-alpha-${{steps.buildnumber.outputs.build_number}}.zip ./Auctionator 
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ steps.buildnumber.outputs.build_number }}-alpha
        release_name: Alpha ${{ steps.buildnumber.outputs.build_number }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Auctionator-alpha-0.0.${{steps.buildnumber.outputs.build_number}}.zip
        asset_name: Auctionator-alpha-0.0.${{steps.buildnumber.outputs.build_number}}.zip
        asset_content_type: application/zip
