name: Curse Build

on:
  push:
    branches:
    - master
    tags:
    - '*'

    paths-ignore:
    - "docs/**"
    - ".github/**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Retail build
      run: cp Auctionator_Mainline.toc Auctionator.toc
    - uses: BigWigsMods/packager@v2
      with:
        args: -p 6124 -a kRNL70Go -g mainline
      env:
        CF_API_KEY: ${{ secrets.plusmouse_curseforge }}
        WAGO_API_TOKEN: ${{ secrets.plusmouse_wago }}

    - name: Setup Vanilla build
      run: cp Auctionator_Vanilla.toc Auctionator.toc
    - uses: BigWigsMods/packager@v2
      with:
        args: -p 6124 -a kRNL70Go -m .pkgmeta_vanilla -g classic
      env:
        CF_API_KEY: ${{ secrets.plusmouse_curseforge }}
        WAGO_API_TOKEN: ${{ secrets.plusmouse_wago }}

    - name: Setup Wrath build
      run: cp Auctionator_Wrath.toc Auctionator.toc
    - uses: BigWigsMods/packager@v2
      with:
        args: -p 6124 -a kRNL70Go -m .pkgmeta_wrath -g wrath
      env:
        CF_API_KEY: ${{ secrets.plusmouse_curseforge }}
        WAGO_API_TOKEN: ${{ secrets.plusmouse_wago }}
