name: Curse Build

on:
  push:
    branches:
    - master
    tags:
    - '*'

    paths-ignore:
    - "docs/**"
    - ".github/**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        path: 'Auctionator'
    - uses: BigWigsMods/packager@master
      with:
        args: -p 6124 -a kRNL70Go
      env:
        GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
        CF_API_KEY: ${{ secrets.plusmouse_curseforge }}
        WAGO_API_TOKEN: ${{ secrets.plusmouse_wago }}
