name: Curse Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create release folder
        run: rsync -av --progress . ./release --exclude .travis.yml --exclude README.md --exclude ./release --exclude .git --exclude spec --exclude .gitignore --exclude .github
      - name: Switch to release folder
        run: cd release
      - name: Derive version
        run: |
          $v=`awk -F'[. ]' '/## Version: / {$5=$5+1;printf "%d.%d.%d-alpha", $3, $4, $5}' Auctionator.toc`
          echo "::set-env name=new_version::$v"
        
