local QUALITY = {
  UNCOMMON = 2,
  RARE = 3,
  EPIC = 4,
}

local ENCHANT_REAGENTS = {
  SOUL_DUST = "172230",
  SACRED_SHARD = "172231",
  ETERNAL_CRYSTAL = "172232",

  GLOOM_DUST = "152875",
  UMBRA_SHARD = "152876",
  VEILED_CRYSTAL = "152877",

  ARKANA = "124440",
  LEYLIGHT_SHARD = "124441",
  CHAOS_CRYSTAL = "124442",

  DRAENIC_DUST = "109693",
  LUMINOUS_SHARD = "111245",
  TEMPORAL_CRYSTAL = "113588",
}

Auctionator.Enchant.DE_TABLE = {
  [LE_EXPANSION_SHADOWLANDS or LE_EXPANSION_9_0] = {
    [QUALITY.UNCOMMON] = {[ENCHANT_REAGENTS.SOUL_DUST] = 2.26},
    [QUALITY.RARE]  = {
      [ENCHANT_REAGENTS.SOUL_DUST]    = 1.5,
      [ENCHANT_REAGENTS.SACRED_SHARD] = 1.41
    },
    [QUALITY.EPIC] = {
      [ENCHANT_REAGENTS.SACRED_SHARD]    = 0.35,
      [ENCHANT_REAGENTS.ETERNAL_CRYSTAL] = 1.06
    }
  },
  [LE_EXPANSION_BATTLE_FOR_AZEROTH] = {
    [QUALITY.UNCOMMON] = {[ENCHANT_REAGENTS.GLOOM_DUST] = 5},
    [QUALITY.RARE]  = {
      [ENCHANT_REAGENTS.GLOOM_DUST]  = 0.55,
      [ENCHANT_REAGENTS.UMBRA_SHARD] = 0.73
    },
    [QUALITY.EPIC] = {
      [ENCHANT_REAGENTS.UMBRA_SHARD]    = 0.4,
      [ENCHANT_REAGENTS.VEILED_CRYSTAL] = 1
    }
  },
  [LE_EXPANSION_LEGION] = {
    [QUALITY.UNCOMMON] = {[ENCHANT_REAGENTS.ARKANA] = 5},
    [QUALITY.RARE]  = {[ENCHANT_REAGENTS.LEYLIGHT_SHARD] = 1},
    [QUALITY.EPIC] = {[ENCHANT_REAGENTS.CHAOS_CRYSTAL] = 1},
  },
  [LE_EXPANSION_WARLORDS_OF_DRAENOR] = {
    [QUALITY.UNCOMMON] = {[ENCHANT_REAGENTS.DRAENIC_DUST] = 2.5},
    [QUALITY.RARE]  = {
      [ENCHANT_REAGENTS.DRAENIC_DUST] = 8.1,
      [ENCHANT_REAGENTS.LUMINOUS_SHARD] = 0.1
    },
    [QUALITY.EPIC] = {[ENCHANT_REAGENTS.TEMPORAL_CRYSTAL] = 1},
  }
}
